# Generated by Django 4.2.1 on 2023-06-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtracer",
            old_name="counter",
            new_name="opened_counter",
        ),
    ]
