# Generated by Django 4.2.1 on 2023-06-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_counter_emailtracer_opened_counter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtracer",
            old_name="lead_id",
            new_name="receiver_email",
        ),
    ]
