# Generated by Django 4.2.1 on 2023-06-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_lead_id_emailtracer_receiver_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtracer",
            name="opened_counter",
        ),
        migrations.RemoveField(
            model_name="emailtracer",
            name="updated_at",
        ),
    ]
